{
  lib,
  buildNpmPackage,
  fetchurl,
}:

buildNpmPackage rec {
  pname = "paca-mcp";
  version = "0.14.1";

  # Fetches the same npm-registry tarball `npx -y @paca-ai/paca-mcp` would
  # pull down (build/index.js ships pre-compiled — no TypeScript build
  # step needed here). The published tarball has no package-lock.json, so
  # ./package-lock.json is a runtime-deps-only lockfile generated by hand
  # once against this exact version (npm install --package-lock-only
  # --omit=dev inside the extracted tarball) and copied in via postPatch.
  src = fetchurl {
    url = "https://registry.npmjs.org/@paca-ai/paca-mcp/-/paca-mcp-${version}.tgz";
    hash = "sha256-Zji9qD9bEDwnQoYizc0xJwWFt65nUktomOIfYjLsNfI=";
  };

  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-OSu36rWKoC8lDhocWSbkivZvnle6Diu9+I6s+a6HCcY=";

  dontNpmBuild = true;

  # Without this, npm's own install-time "prepare" lifecycle hook still
  # fires and re-runs the "build" script (tsc), which isn't available —
  # the lockfile only resolves runtime deps, since build/index.js already
  # ships pre-compiled and nothing here needs devDependencies.
  npmFlags = [ "--ignore-scripts" ];

  # Upstream's own bin name ("paca") is too generic/collision-prone for a
  # PATH-wide install — this is an MCP server referenced by explicit
  # command in an agent's MCP config, not invoked interactively, so the
  # name doesn't need to match upstream's.
  postInstall = ''
    mv $out/bin/paca $out/bin/paca-mcp
  '';

  meta = {
    description = "Paca MCP server — API access for AI agents managing a Paca workspace";
    homepage = "https://github.com/Paca-AI/paca/tree/master/apps/mcp";
    license = lib.licenses.asl20;
    mainProgram = "paca-mcp";
  };
}
