{
  lib,
  buildNpmPackage,
  fetchurl,
}:

buildNpmPackage rec {
  pname = "windmill-cli";
  version = "1.824.1";

  # The published tarball ships a bundled esm/main.js, so there is nothing to
  # build. It has no lockfile, so ./package-lock.json is generated by
  # bin/update-windmill-cli against this exact version and copied in via
  # postPatch.
  #
  # Keep this in step with the Windmill server version (services/windmill.nix
  # in the colmena repo): the CLI and server are versioned together and a
  # mismatch tends to show up as confusing `wmill sync` errors.
  src = fetchurl {
    url = "https://registry.npmjs.org/windmill-cli/-/windmill-cli-${version}.tgz";
    hash = "sha256-1hmcEcNcZllrvSHzBkbnkobepbIZCfRbRQjSwVjEP+I=";
  };

  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-4v/hfbmfzbw2yMC4l73XeAxLfbUEw8t4Rnm1F3DMK2Y=";

  dontNpmBuild = true;

  meta = {
    description = "CLI for Windmill (wmill): workspace sync, script and flow deploys";
    homepage = "https://www.windmill.dev/docs/advanced/cli";
    license = lib.licenses.asl20;
    mainProgram = "wmill";
  };
}
