{
  lib,
  buildNpmPackage,
  fetchurl,
  jq,
  makeWrapper,
  acli,
}:

buildNpmPackage rec {
  pname = "jira-axi";
  version = "1.0.4";

  # The published tarball ships a prebuilt dist/ (the monorepo's
  # @atlassian-axi/core is bundled in by tsup) and skills/jira-axi/SKILL.md,
  # so there's no pnpm/turbo workspace build to reproduce here. It has no
  # lockfile, so ./package-lock.json is generated by bin/update-atlassian-axi
  # against this exact version and copied in via postPatch.
  src = fetchurl {
    url = "https://registry.npmjs.org/jira-axi/-/jira-axi-${version}.tgz";
    hash = "sha256-b2kyWWiZu1zHu98KnamTuS9hERavhlqBSvYY1jcNnPU=";
  };

  # devDependencies only holds a pnpm `workspace:*` reference npm can't
  # resolve, and nothing at runtime needs it.
  postPatch = ''
    ${lib.getExe jq} 'del(.devDependencies)' package.json > package.json.tmp
    mv package.json.tmp package.json
    cp ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-Mql290wU2sSLQhoLF37C7/dgRBJ43G5/vSry3W3y0Nc=";

  dontNpmBuild = true;

  nativeBuildInputs = [ makeWrapper ];

  # Every command shells out to acli. Suffixed so a separately installed
  # acli still wins; either way auth is acli's own login.
  #
  # Upstream's skill defaults to `npx -y jira-axi@latest`, which would bypass
  # this pinned build, and offers `setup hooks`/`update`, which need a global
  # npm install and a writable ~/.claude/settings.json. Swap that guidance for
  # a note that the binary is already on PATH. The greps fail the build if a
  # reworded upstream skill slips past the patterns.
  postInstall = ''
    wrapProgram $out/bin/jira-axi --suffix PATH : ${lib.makeBinPath [ acli ]}

    skill=$out/lib/node_modules/jira-axi/skills/jira-axi/SKILL.md
    awk '
      /^You do not need jira-axi installed/ {
        print "`jira-axi` is installed on `PATH` by nix, pinned to the version this skill documents. Run it directly as `jira-axi <command>`, never through `npx` or a global npm install. `setup hooks` and `update` do not apply to this install."
        next
      }
      /npx|@latest|npm i -g|What the hook adds|Every command below behaves identically|setup hooks` to install/ { next }
      { print }
    ' "$skill" | cat -s > SKILL.md.tmp
    grep -q 'installed on `PATH` by nix' SKILL.md.tmp
    if grep -v 'installed on `PATH` by nix' SKILL.md.tmp | grep -Eq 'npx|npm i -g'; then
      echo "SKILL.md still points at npx/npm; update the awk patterns" >&2
      exit 1
    fi
    mv SKILL.md.tmp "$skill"
  '';

  meta = {
    description = "Agent-ergonomic Jira CLI backed by Atlassian's acli";
    homepage = "https://github.com/emilchristensen/atlassian-axi/tree/main/packages/jira-axi";
    license = lib.licenses.mit;
    mainProgram = "jira-axi";
  };
}
